ALTER SEQUENCE brand_id_seq INCREMENT BY 50;
ALTER SEQUENCE note_id_seq INCREMENT BY 50;
ALTER SEQUENCE accord_id_seq INCREMENT BY 50;
ALTER SEQUENCE occasion_tag_id_seq INCREMENT BY 50;
ALTER SEQUENCE perfume_id_seq INCREMENT BY 50;
ALTER SEQUENCE perfume_note_id_seq INCREMENT BY 50;
ALTER SEQUENCE perfume_accord_id_seq INCREMENT BY 50;
ALTER SEQUENCE perfume_season_score_id_seq INCREMENT BY 50;
